---
title: "US Police Shootings"
author: "Ketan Mittal"
date: "`r Sys.Date()`"
output: html_document
--- 

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggplot2)
```

```{r}
shooting_data <- read_csv("shootings.csv")
attach(shooting_data)
```
```{r}
state_data <- 
  shooting_data %>% 
  mutate(state = case_when(
    state == "CA" | state == "NV" |state == "AK" | state == "HI" ~ "West", 
    state == "OR"| state == "WA"| state ==  "ID"| state ==  "MT"| state ==  "WY" ~ "North West", 
    state == "UT"| state ==  "AZ"| state ==  "NM"| state ==  "CO"| state ==  "TX"| state ==  "OK" ~ "South West", 
    state == "ND"| state ==  "SD"| state ==  "NE"| state ==  "KS"| state ==  "MN"| state ==  "IA"| state ==  "MO"| state ==  "WI"| state ==  "IL"| state ==  "IN"| state ==  "MI"| state ==  "OH"| state ==  "KY" ~ "Mid-West",
    state == "AR"| state ==  "LA"| state ==  "TN"| state ==  "MS"| state ==  "AL"| state ==  "GA"| state ==  "FL"| state ==  "SC"| state ==  "NC" ~ "South East",
    state == "WV"| state ==  "VA"| state ==  "MD"| state ==  "DE"| state ==  "PA"| state ==  "NY"| state ==  "NJ"| state == "DC" ~ "Mid-Atlantic",
    state == "VT"| state ==  "CT"| state ==  "MA"| state ==  "NH"| state ==  "ME"| state ==  "RI" ~ "North East"
  ))
ggplot(state_data, aes(x = factor(state), fill = race)) + 
  geom_bar(aes(y = ((..count..)/sum(..count..))), stat = "count") +
  scale_y_continuous(labels=scales::percent) +
  labs(title = "The Number of Police Killings by State Region described by Race", y = "percentage", fill = "Race", x = "State Regions")
       
```

```{r}
ggplot(state_data, aes(x = factor(race), fill = race)) + 
  geom_bar(aes(y = ((..count..)/sum(..count..))), stat = "count") +
  geom_text(aes(label = scales::percent(round((..count..)/sum(..count..), 2)),
                y = ((..count..)/sum(..count..))), stat = "count", vjust = -.25) + 
  scale_y_continuous(labels=scales::percent) + 
  labs(title = "Number of Police Killings by Race in Percent", y = "percentage", fill = "Race", x = "Race")
```
```{r}
gov_site <- data.frame(
    race = c("Asian", "Black", "Hispanic", "Native", "Other", "White"),
    percentages = c(6.1, 13.6, 18.9, 1.3, .8, 59.3)
    )
ggplot(gov_site, aes(x = factor(race), fill = race)) + 
  geom_bar(aes(y = (percentages/100)), stat = "Identity") +
  geom_text(aes(label = scales::percent(percentages/100),
                y = percentages/100), stat = "Identity", vjust = -.25) + 
  scale_y_continuous(labels=scales::percent) + 
  labs(title = "Percent of People in America", y = "percentage", fill = "Race", x = "Race")
```
```{r}

```






